// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sehvecwbatutfxhsozmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlaHZlY3diYXR1dGZ4aHNvem11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzI3ODYsImV4cCI6MjA1ODI0ODc4Nn0.PqIVP9PbVC5tekRxAGjfnISo2qU_-78bLEB_p7XXKAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);