// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbawbhaslcdlwywisuvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYXdiaGFzbGNkbHd5d2lzdXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNDQzNDYsImV4cCI6MjA1NzkyMDM0Nn0.fzRTRwLLC_FQzLeX510EEyPnG-B5-EZxPGJMGE9yJQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);